// Category → natural-language synonym map for Stage 2.5 lexical overlap.
//
// Sourced from the canonical 53-category taxonomy in
// quaestor-vendor-registry/docs/categories.md. For each category we list
// the canonical id (kebab-case), the space-form (`vector db` for `vector-db`),
// and 4-8 phrases an authoring user might use to describe spend authorized
// against that category in mandate-intent text.
//
// Rules of thumb when extending:
//   - Synonyms are matched against intent text after lowercasing and
//     punctuation-stripping; word-boundary check is applied so a synonym
//     can't appear as a substring of a longer word.
//   - Multi-word synonyms must be the most-natural surface form; no regex.
//   - Don't pollute one category's list with another category's words —
//     if a phrase is genuinely ambiguous (e.g. "compute" applies to both
//     cloud-compute and ml-infra), include it in both.
//   - Avoid single-word synonyms that are common English ("data", "api",
//     "tools") — they cause false matches on unrelated intents. Prefer
//     two-word phrases.
//
// Subdomain-only categories `api` and `admin` are intentionally absent.

export const CATEGORY_SYNONYMS: Record<string, readonly string[]> = {
  // ── Cloud + compute ──
  'cloud-compute': [
    'cloud compute',
    'cloud hosting',
    'cloud infrastructure',
    'cloud server',
    'cloud servers',
    'iaas',
    'paas',
    'vps',
    'virtual machine',
    'container hosting',
    'function runtime',
    'serverless',
    'saas hosting',
    'backend infrastructure',
    'server side compute',
    'production hosting',
    'staging cluster',
  ],
  'edge-compute': [
    'edge compute',
    'edge function',
    'edge functions',
    'edge runtime',
    'edge worker',
    'edge workers',
    'edge network',
  ],
  cdn: ['cdn', 'content delivery', 'content delivery network', 'dns', 'image delivery'],
  storage: [
    'object storage',
    'block storage',
    'file storage',
    'cloud storage',
    'blob storage',
    's3',
    'storage costs',
    'storage bucket',
    'backups',
    'backup',
  ],

  // ── ML / AI ──
  'ml-infra': [
    'ml infra',
    'ml infrastructure',
    'gpu',
    'gpu compute',
    'gpu hosting',
    'gpu cluster',
    'gpu rental',
    'training infrastructure',
    'training compute',
    'fine tuning',
    'fine-tuning',
  ],
  'ml-inference': [
    'ml inference',
    'ai inference',
    'llm inference',
    'model inference',
    'ai api',
    'ai apis',
    'language model',
    'large language model',
    'llm api',
    'llm apis',
    'gpt',
    'claude api',
    'openai api',
    'anthropic api',
    'embedding api',
    'embeddings api',
    'support bot',
    'inference credits',
  ],
  'ml-training-data': [
    'training data',
    'dataset',
    'datasets',
    'rlhf',
    'data labeling',
    'data annotation',
    'ml tooling',
  ],

  // ── Developer tooling ──
  'developer-tools': [
    'developer tools',
    'dev tools',
    'engineering tools',
    'engineering subscriptions',
    'engineering team',
    'engineering operations',
    'engineering coffee',
    'devex',
    'developer experience',
    'developer tooling',
    'api client',
    'debugger',
    'build tools',
    'domain registration',
    'dns registration',
    'dev resources',
    'dev resource',
    'workflow orchestration',
    'background task',
    'background tasks',
    'agent project',
    "agent's project",
    "agent's own project",
  ],
  ide: ['ide', 'code editor', 'codespace', 'codespaces', 'cloud editor', 'jetbrains', 'replit'],
  'version-control': [
    'version control',
    'source control',
    'git hosting',
    'code hosting',
    'repository hosting',
    'github',
    'gitlab',
    'bitbucket',
    'copilot',
  ],
  'ci-cd': [
    'ci',
    'cd',
    'ci cd',
    'ci/cd',
    'continuous integration',
    'continuous delivery',
    'build pipeline',
    'ci pipeline',
    'ci minutes',
    'github actions',
  ],

  // ── Observability ──
  monitoring: ['monitoring', 'metrics', 'alerting', 'uptime', 'health check', 'analytics'],
  observability: [
    'observability',
    'distributed tracing',
    'tracing',
    'apm',
    'application monitoring',
  ],
  logging: ['logging', 'log aggregation', 'log management', 'audit logs'],
  'error-tracking': [
    'error tracking',
    'error capture',
    'crash reporting',
    'exception tracking',
    'sentry',
  ],

  // ── Data ──
  databases: [
    'database',
    'databases',
    'oltp',
    'olap',
    'managed db',
    'sql database',
    'nosql database',
    'postgres',
    'mysql',
    'mongodb',
    'data warehouse',
    'warehouse tooling',
    'stateful agent data',
    'stateful data',
  ],
  caching: ['cache', 'caching', 'redis', 'memcached', 'in memory cache'],
  search: ['search', 'full text search', 'hybrid search', 'search index'],
  'vector-db': [
    'vector db',
    'vector database',
    'embedding store',
    'embedding database',
    'vector store',
    'pinecone',
  ],
  'data-broker': ['data broker', 'data aggregator', 'third party data'],
  'data-api': [
    'data api',
    'weather api',
    'maps api',
    'geo api',
    'mapping api',
    'external data api',
    'specialized data',
    'research subscriptions',
    'research subscription',
    'image transformation',
  ],
  'data-pipeline': [
    'data pipeline',
    'etl',
    'elt',
    'data ingestion',
    'streaming etl',
    'data orchestration',
    'data sync',
    'data transformation',
  ],

  // ── Identity + secrets ──
  auth: [
    'auth',
    'authentication',
    'login',
    'sign in',
    'user authentication',
    'auth0',
    'clerk',
    '2fa',
    'two factor',
  ],
  identity: [
    'identity verification',
    'kyc',
    'identity graph',
    'ssl certificate',
    'tls certificate',
    'certificate',
  ],
  sso: ['sso', 'single sign on', 'enterprise auth', 'okta'],
  'secrets-management': [
    'secrets management',
    'secret storage',
    'secret rotation',
    'vault',
    'ssl certificate',
    'tls certificate',
    'certificate',
  ],

  // ── Money ──
  payments: [
    'payments',
    'payment processing',
    'card processing',
    'payment gateway',
    'billing',
    'subscription billing',
    'checkout',
    'micro payments',
    'micro-payments',
    'payment processor',
    'payment processor fees',
    'stripe',
  ],
  fintech: ['fintech', 'brokerage', 'neobank', 'embedded finance', 'plaid', 'mercury', 'brex'],
  banking: ['banking', 'bank account', 'banking api', 'wire transfer', 'ach'],
  accounting: [
    'accounting',
    'bookkeeping',
    'invoicing',
    'financial accounting',
    'back office accounting',
    'back-office accounting',
    'quickbooks',
    'xero',
  ],

  // ── Communication ──
  'email-api': [
    'email api',
    'transactional email',
    'email delivery',
    'email sending',
    'password reset',
    'password resets',
    'sendgrid',
    'mailgun',
    'postmark',
  ],
  'sms-api': [
    'sms api',
    'sms',
    'text messaging',
    'programmable messaging',
    'sms credits',
    '2fa sms',
    '2fa flow',
    'twilio',
  ],
  'voice-api': [
    'voice api',
    'programmable voice',
    'voice calling',
    'voice agent',
    'real time audio',
    'real-time audio',
    'audio streaming',
    'twilio voice',
  ],
  'comms-api': [
    'chat api',
    'video api',
    'realtime chat',
    'real time chat',
    'real-time chat',
    'live chat infrastructure',
    'video streaming',
    'real time messaging',
    'real-time messaging',
    'conversational voice',
    'websocket',
    'pub sub',
    'pub/sub',
    'pub-sub',
  ],

  // ── Productivity / SaaS ──
  productivity: [
    'productivity',
    'productivity tools',
    'productivity software',
    'notes app',
    'task tracking',
    'todo app',
    'note taking',
    'notion',
    'airtable',
  ],
  collaboration: [
    'collaboration',
    'team chat',
    'video conferencing',
    'team meeting',
    'communication tools',
    'slack',
    'zoom',
    'teams',
    'scheduling',
    'calendar',
  ],
  'project-management': [
    'project management',
    'issue tracker',
    'task tracker',
    'pm tool',
    'engineering support',
    'support tools',
    'linear',
    'jira',
    'asana',
  ],
  design: ['design tools', 'design software', 'design subscriptions', 'whiteboard', 'figma', 'stock photo', 'product tools'],
  'content-cms': [
    'cms',
    'content management',
    'headless cms',
    'knowledge base',
    'documentation content',
    'blog post',
    'launch blog',
    'stock photo',
  ],
  marketing: ['marketing', 'marketing automation', 'email marketing', 'esp', 'crm', 'customer support', 'customer support stack'],

  // ── Crypto ──
  'crypto-onchain': ['onchain', 'on chain', 'on-chain', 'layer 1', 'layer 2', 'l1', 'l2', 'blockchain'],
  'crypto-cex': ['centralized exchange', 'crypto exchange', 'cex', 'coinbase', 'binance'],
  'crypto-bridge': ['crypto bridge', 'cross chain bridge', 'bridge', 'wormhole'],
  'crypto-defi': ['defi', 'decentralized finance', 'on chain defi', 'liquidity pool', 'uniswap'],

  // ── Hardware / retail ──
  hardware: ['hardware'],
  electronics: ['electronics', 'components', 'chips', 'boards', 'sensors', 'soldering'],
  'lab-supplies': ['lab supplies', 'laboratory', 'consumables', 'reagents'],
  books: ['book', 'books', 'bookstore', 'publisher', 'digital book', 'ebook'],
  'retail-consumer': [
    'retail',
    'consumer retail',
    'consumer goods',
    'household goods',
    'general merchandise',
    'amazon retail',
  ],

  // ── Daily life / risk-flagged ──
  'food-delivery': [
    'food delivery',
    'food order',
    'meal delivery',
    'grocery delivery',
    'takeout',
    'doordash',
    'uber eats',
    'instacart',
  ],
  transit: ['transit', 'ride hail', 'rideshare', 'ride share', 'mobility', 'uber', 'lyft'],
  gambling: ['gambling', 'sportsbook', 'lottery', 'casino', 'wagering', 'betting'],
};

// All canonical category slugs (excluding subdomain-only `api`, `admin`)
// covered above. Used by callers/tests for completeness checks.
export const KNOWN_CATEGORIES: ReadonlySet<string> = new Set(Object.keys(CATEGORY_SYNONYMS));
